### ISSUE TITLE
폴링 블록 추가할 때 NoClassDefFoundError 오류 발생

### ISSUE THREAD

**Issue by dytroc** [noonmaru/parkour-maker#12]
**상황:** 
파쿠르 메이커를 빌드해가지고 간단한 파쿠르를 만들 때 아무런 문제는 없었지만, ON/OFF 블록이나 폴링 블록을 추가할 때는 FakeSupport에서 NoClassDefFoundError 오류가 갑자기 납니다.

**추가 정보:** 
서버 플러그인 폴더엔 tap-2.8.8-dist.jar, parkour-maker-0.3-dist.jar, worldedit-bukkit-7.1.0.jar, ProtocolLib.jar (1.16)과 kotlin-1.3.72-lib.jar 파일들이 있습니다. 쓰고 있는 서버는 1.16.2 PaperMC-161입니다.

**로그:**

```
[16:01:23 INFO]: DytroPlays issued server command: /parkour start demo
java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.tap.fake.FakeSupportKt
[16:01:23 WARN]:        at com.github.noonmaru.tap.fake.internal.FakeEntityServerImpl.spawnEntity(FakeEntityServerImpl.kt:60)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.ToggleBlock$ToggleData.onInitialize(ParkourBlock.kt:305)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.Challenge$parseBlocks$1.invoke(Challenge.kt:47)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.Challenge$parseBlocks$1.invoke(Challenge.kt:11)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.Challenge.forEachBlocks(Challenge.kt:133)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.Challenge.parseBlocks$parkour_maker(Challenge.kt:44)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.Level.startChallenge(Level.kt:83)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour.start(KommandParkour.kt:90)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour.access$start(KommandParkour.kt:20)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour$register$1$3$1$1.invoke(KommandParkour.kt:41)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour$register$1$3$1$1.invoke(KommandParkour.kt:20)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.shaded.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:90)
[16:01:23 WARN]:        at com.github.noonmaru.parkourmaker.shaded.KommandAdapter.onCommand(KommandDispatcher.kt:223)
[16:01:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:01:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:01:23 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1902)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1713)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[16:01:23 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:01:23 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Apple6050** [comment]
아직 이 플러그인은 1.16.2를 지원하지 않습니다.
PaperMC 1.16.1로 버전을 낮추어주시길 바랍니다.

**Comment by ghost** [comment]
@dytroInc 아직 이 플러그인은 1.16.2를 지원하지 않습니다.
PaperMC 1.16.1로 버전을 낮추어주시길 바랍니다.

**Comment by ghost** [comment]
@dytroInc PaperMC-138빌드 이용바랍니다.

**Comment by dytroc** [comment]
> @dytroInc 아직 이 플러그인은 1.16.2를 지원하지 않습니다.
> PaperMC 1.16.1로 버전을 낮추어주시길 바랍니다.

그렇군요, 감사합니다.
