### ISSUE TITLE
Issues + Idea

### ISSUE THREAD

**Issue by ghost** [noonmaru/parkour-maker#15]
한 사람이 파쿠르를 플레이 하는 도중 다른 사람이 파쿠르를 시작하려고 하면 콘솔 Warning

```
[12:06:24 INFO]: (PlayerName) issued server command: /parkour start 5
[12:06:25 INFO]: BaeHyeonWoo issued server command: /parkour start 5
[12:06:25 WARN]: java.lang.IllegalStateException: Challenge is already in progress.
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.Level.startChallenge(Level.kt:79)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour.start(KommandParkour.kt:95)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour.access$start(KommandParkour.kt:19)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour$register$1$3$1$3.invoke(KommandParkour.kt:48)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.command.KommandParkour$register$1$3$1$3.invoke(KommandParkour.kt:19)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.shaded.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:90)
[12:06:25 WARN]:        at com.github.noonmaru.parkourmaker.shaded.KommandAdapter.onCommand(KommandDispatcher.kt:223)
[12:06:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:06:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:06:25 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1913)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1724)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[12:06:25 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:06:25 WARN]:        at java.lang.Thread.run(Unknown Source)
```

게임 자체 플레이 지장은 없습니다.

Host : Windows 10 (1909)
Minecraft Release : 1.16.1
Server : Paper-138

Plugins : 
```
kotlin-1.4.0-lib
parkour-maker-0.3-dist
ProtocolLib (4.6.0)
tap-2.8.8-dist
worldedit-bukkit-7.2.0-beta-04
```

.
.
.
.
.

**Comment by ghost** [comment]
~~저만 그런건지는 모르겠는데 파쿠르 만들었다, 중지했다, 포기했다 등등 메시지가 안떠요
(똑같은 조건에서 어떤 명령을 치든간에 "채팅에만" 아무런 메시지가 안뜹니다. 게임에 지장은 없습니다. Title, Firework 등등 잘됩니다)~~

(+ 관리중 문제인것 같아서 다시 테스트해보겠습니다. 죄송합니다.)

**Comment by ghost** [comment]
+ 특정 블럭을 밟으면 지나간 모든 구조물들이 리셋되는 블럭이 필요할거 같습니다.
+ 발사기 화살 적용
+ 파쿠르 제작시 범위 Limit 적용 (...)

**Comment by ghost** [comment]
Currently having some works to be done. I'll comment again if this issue is completely done.
