### ISSUE TITLE
서버오류

### ISSUE THREAD

**Issue by chipppppp** [noonmaru/parkour-maker#25]
플러그인끼고서버켰는데

[08:19:52 ERROR]: Error occurred while disabling ParkourMaker v0.3 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property fakeEntityServer has not been initialized
        at com.github.noonmaru.parkourmaker.ParkourMaker.getFakeEntityServer(ParkourMaker.kt:35) ~[?:?]
        at com.github.noonmaru.parkourmaker.plugin.ParkourMakerPlugin.onDisable(ParkourMakerPlugin.kt:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:834) [?:?] 이렇게 뜨네요 해결방안좀 알려주실분있나요

**Comment by chipppppp** [comment]
> 플러그인 끼고 서버 궁금는데
> 
> [08:19:52 ERROR] : ParkourMaker v0.3을 비활성화하는 동안 오류가 발생했습니다 (최신 상태입니까?)
> kotlin.UninitializedPropertyAccessException : lateinit 속성 fakeEntityServer가
> com.github.noonmaru.parkourmaker.ParkourMaker.getFakeEntityServer (ParkourMaker에서 초기화되지 않았습니다. .kt : 35) ~ [? :?]
> at com.github.noonmaru.parkourmaker.plugin.ParkourMakerPlugin.onDisable (ParkourMakerPlugin.kt : 28) ~ [? :?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled (JavaPlugin.java:265) ~ [patched_1.16.1.jar : git-Paper-138]
> at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin (JavaPluginLoader.java:415) ~ [patched_1.16.1.jar : git- Paper-138]
> at org.bukkit.plugin.SimplePluginManager.disablePlugin (SimplePluginManager.java:516) ~ [patched_1.16.1.jar : git-Paper-138]
> org.bukkit.plugin.java.JavaPluginLoader.enablePlugin (JavaPluginLoader.java:384) ~ [patched_1.16.1.jar : git-Paper-138]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin (SimplePluginManager.java:483) ~ [patched_1.16.1.jar : git-Paper-138]
> at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin (CraftServer.java:500) ~ [patched_1.16.1.jar : git-Paper-138]
> at org. bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins (CraftServer.java:414) ~ [patched_1.16.1.jar : git-Paper-138]
> at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld (MinecraftServer.java:471) ~ [patched_1.16.1.jar : 자식 용지-138]
> net.minecraft.server.v1_16_R1.DedicatedServer.init (DedicatedServer.java:241)에서 ~ [patched_1.16.1.jar : 자식 용지-138]
> net.minecraft.server.v1_16_R1.MinecraftServer.v (MinecraftServer.java:941) ~ [patched_1.16.1.jar : git-Paper-138]
> net.minecraft.server.v1_16_R1.MinecraftServer.lambda $ a $ 0 (MinecraftServer .java : 177) ~ [patched_1.16.1.jar : git-Paper-138]
> at java.lang.Thread.run (Thread.java:834) [? :?] 이렇게 뜨 네요 해결 방안 좀 알려 주실 분 있나요

**Comment by ghost** [comment]
**이슈 여러개 다시는 것보다, 직접 찾아서 해결해보는 것을 추천드리며, 이슈는 원래 질문 게시판이 아니라는 점을 감안해주셨으면 합니다.**

Tap을 2.8.8로, ProtocolLib 4.6.0, WorldEdit을 7.1.0으로 넣으신거 맞나요?

**Comment by chipppppp** [comment]
> **이슈 여러개 다시는 것보다, 직접 찾아서 해결해 보는 것을 추천 드리며, 이슈는 원래 질문 게시판이 아니라는 점을 감안해 주셨으면합니다.**
> 
> Tap을 2.8.8로, ProtocolLib 4.6.0, WorldEdit을 7.1.0으로 추천 신거 맞나요?

앞으로 그렇게 하겠습니다 그리고 Tap플러그인은너무빌드하기까다롭고어렵더라구요..이해도못하겠고혹시빌드하는방법말고다른방법은없나요

**Comment by seues** [comment]
Release를 다운 받으면 되겠죠..?

**Comment by ghost** [comment]
> > **이슈 여러개 다시는 것보다, 직접 찾아서 해결해 보는 것을 추천 드리며, 이슈는 원래 질문 게시판이 아니라는 점을 감안해 주셨으면합니다.**
> > 
> > Tap을 2.8.8로, ProtocolLib 4.6.0, WorldEdit을 7.1.0으로 추천 신거 맞나요?
> 
> 앞으로 그렇게 하겠습니다 그리고 Tap플러그인은너무빌드하기까다롭고어렵더라구요..이해도못하겠고혹시빌드하는방법말고다른방법은없나요

[Tap 2.8.8](https://github.com/noonmaru/tap/releases/download/2.8.8/tap-2.8.8-dist.jar)

**Comment by ghost** [comment]
적용후 해결되면 이슈닫아주세요.

**Comment by chipppppp** [comment]
> 적용 후 해결되면 이슈 닫아주세요.

항상 감사합니다
