### ISSUE TITLE
[불확실] 파쿠르 메이커 작동시 오류 발생

### ISSUE THREAD

**Issue by ghost** [noonmaru/parkour-maker#3]
파쿠르 메이커를 적용시키고 월엣으로 리전 설정한뒤 파쿠르를 시작하려고 하면 오류가 발생합니다. (혹 파쿠르가 이미 있을때 사람이 접속하면 그 사람은 파쿠르를 플레이 하지 못합니다.)
오류는 이와 같습니다...
[14:44:07] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.entity.ArmorStand.getItem(Lorg/bukkit/inventory/EquipmentSlot;)Lorg/bukkit/inventory/ItemStack;
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.tap.protocol.EntityPacketSupport.equipment(PacketSupport.kt:104)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.tap.fake.FakeArmorStand.spawnTo(FakeArmorStand.kt:111)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.tap.fake.FakeEntity.updateTrackers$api(FakeEntity.kt:266)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.tap.fake.FakeManager.createFakeEntity(FakeManager.kt:54)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.ToggleBlock$ToggleData.onInitialize(ParkourBlock.kt:297)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.Challenge$parseBlocks$1.invoke(Challenge.kt:44)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.Challenge$parseBlocks$1.invoke(Challenge.kt:10)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.ChallengeKt.forEachBlocks(Challenge.kt:119)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.Challenge.parseBlocks$parkour_maker(Challenge.kt:41)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.Level.startChallenge(Level.kt:85)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.parkourmaker.command.CommandStart.onCommand(Commands.kt:93)
[14:44:07] [Server thread/WARN]:        at com.github.noonmaru.tap.command.CommandSet.onCommand(CommandSet.kt:165)
[14:44:07] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:44:07] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:44:07] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[14:44:07] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[14:44:07] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

직접 /reload를 치면 이후 오류가 발생되지는 않으나, 파쿠르를 제작하거나 새 사람이 들어오면 리로딩을 계속 해야하는 번거로움이 있습니다.
수정 : 파쿠르를 제작하고 나서 오류가 안나는 경우도 있네요.. 왜인지는 모르겠습니다.
이에 대해서 이슈를 남깁니다. (문제시 닫겠습니다.)

**Comment by patrick-choe** [comment]
혹시 실행 환경을 알려주실 수 있나요? (Java 버젼, 운영체제, 버킷종류/버전, tap버전)

**Comment by ghost** [comment]
> 혹시 실행 환경을 알려주실 수 있나요? (Java 버젼, 운영체제, 버킷종류/버전, tap버전)

Java SE Development Kit 8 (jdk 1.8.0)
Windows 10
1.15.2-R0.1-SNAPSHOT
Tap 2.3.3입니다.

**Comment by patrick-choe** [comment]
> > 혹시 실행 환경을 알려주실 수 있나요? (Java 버젼, 운영체제, 버킷종류/버전, tap버전)
> 
> Java SE Development Kit 8 (jdk 1.8.0)
> Windows 10
> 1.15.2-R0.1-SNAPSHOT
> Tap 2.3.3입니다.

오류의 내용을 보면 getItem이라는 함수가 없다는 것으로 보이는데, tap 2.3.3 에는 분명히 있습니다.. 저도 무슨 문제인지는 잘 모르겠네요.. 

> `[14:44:07] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.entity.ArmorStand.getItem(Lorg/bukkit/inventory/EquipmentSlot;)Lorg/bukkit/inventory/ItemStack;`
이부분이 문제의 부분인 것 같긴 한데,,,

**Comment by patrick-choe** [comment]
@BaeHyeonWoo-1017 아 혹시 1.15.2-R0.1이면 spigot 빌드인가요?
코드상 `FakeArmorStand`의 `getItem()`은 바로` org.bukkit.entity.ArmorStand.getItem`으로 이어지는데, 이 getItem은 오직 paper 빌드에서만 있습니다 (paper은 spigot 빌드의 확장된것이라고 보면 될 것 같습니다) papermc.io 에서 paper빌드를 받아서 테스트해보시는 것은 어떨까요?

**Comment by ghost** [comment]
엇 시도해보겠습니다! (시도할 날이 오면 시도 후 성공시 이슈 닫겠습니다)

**Comment by ghost** [comment]
서버를 Spigot으로열어서 문제가 되었네요.
paper로 여니 가짜 엔티티 (가상 블록)이 보입니다.
patrick-mc님 감사합니다.
이슈 닫겠습니다.
