### ISSUE TITLE
[버그(?) 및 플러그인 사용 문의]

### ISSUE THREAD

**Issue by fi-xz** [noonmaru/parkour-maker#6]

**Comment by patrick-choe** [comment]
- /parkour quit 명령어
> 사용시 발생한 오류를 알려주실수 있나요? 오류 발생이라고 하면 어떤 오류인지 확인할 수 없습니다. stacktrace도 첨부해주시면 감사하겠습니다.

- 도착 블록
> 금 블록을 사용해주시면 됩니다

- 커맨드 블록
> 이는 어떻게 보면 어쩔수 없는 요소로, 해당 파쿠르 종료시 파쿠르 이전의 상태로 돌아가기 위해 해당 리전 저장해둔 것을 덮어쓰게 됩니다. 이 과정에서, 커맨드 블록과 버튼 또한 덮어쓰기 되는데, 이때 본래 상태와 관계 없이, 새로운 커맨드 블록과 새로운 **활성화**된 레버를 붙여넣게 되어, 자연스럽게 실행됩니다. 이를 해결하시려면, 세이브 하기 이전에 커맨드를 **끈** 상태로 start해주시면 될것 같습니다. 감사합니다.

**Comment by patrick-choe** [comment]
> 빌드 속도의 경우, 컴퓨터의 성능, 저장장치의 속도에 따라 달라질 수 있으며, 마인크래프트 관련 프로젝트를 처음 빌드하시는 경우, dependency들을 새로 다운받아서 빌드해야 해서 속도가 느릴 수 있습니다.

**Comment by qogusdn1017-BHW-SecondAccount** [comment]
[04:08:21] [Server thread/INFO]: Pillowprism_ issued server command: /parkour quit Pillowprism_
[04:08:21] [Server thread/WARN]: java.lang.NoSuchMethodError: com.github.noonmaru.tap.command.ArgumentList.isEmpty()Z
[04:08:21] [Server thread/WARN]: 	at com.github.noonmaru.parkourmaker.command.CommandQuit.onCommand(CommandQuit.kt:22)
[04:08:21] [Server thread/WARN]: 	at com.github.noonmaru.tap.command.CommandSet.onCommand(CommandSet.kt:165)
[04:08:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:08:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[04:08:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1634)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035)
[04:08:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950)
[04:08:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

컴퓨터 사용 불가 상태라 로그만이라도 올립니다...

(개인적으로는 빌드가 아직도 의문이네요.. 0.1 빌드할때는 5분밖에 안걸렸는데 0.2에서 30분이나 걸리니... 제 문제일수도 있고...)

**Comment by patrick-choe** [comment]
> java.lang.NoSuchMethodError
혹시 tap 등의 필요한 라이브러리를 넣지 않으셨거나, 아니면 버전을 잘못 넣으신게 아닐까 조심스럽게 추론해봅니다.

> https://github.com/noonmaru/tap/commit/ee046b3062be1aa90e66e59cb01e7bef078a99d8#diff-b625f1f696197ba1cba067c04c2e3c0e
noonmaru님의 5월 3일 커밋에서 Boolean 값을 리턴하는 isEmpty() 함수가 사라졌습니다. 그 이전에 릴리즈된 버젼 사용이 필요해 보입니다. (2.3.1 권장) 

감사합니다.

**Comment by patrick-choe** [comment]
0.1 빌드와 0.2 빌드에서 큰 차이는 없습니다 (gradle 6.4, kotlin 1.3.72 업데이트, 기능 추가)
따라서 크게 영향을 준 요인은 보이지 않으나, gradle, kotlin에 대한 캐시가 없을 경우 느릴 수 있지 않을까 생각됩니다.

빌드 중 오류만 없었다면 큰 문제는 없을겁니다.

**Comment by ghost** [comment]
> > java.lang.NoSuchMethodError
> > 혹시 tap 등의 필요한 라이브러리를 넣지 않으셨거나, 아니면 버전을 잘못 넣으신게 아닐까 조심스럽게 추론해봅니다.
> 
> > [noonmaru/tap@ee046b3#diff-b625f1f696197ba1cba067c04c2e3c0e](https://github.com/noonmaru/tap/commit/ee046b3062be1aa90e66e59cb01e7bef078a99d8#diff-b625f1f696197ba1cba067c04c2e3c0e)
> > noonmaru님의 5월 3일 커밋에서 Boolean 값을 리턴하는 isEmpty() 함수가 사라졌습니다. 그 이전에 릴리즈된 버젼 사용이 필요해 보입니다. (2.3.1 권장)
> 
> 감사합니다.

아 왠지 NoSuchMethod가 왜 뜨나 했네요.. 테스트 후 이슈 닫겠습니다.

**Comment by qogusdn1017-BHW-SecondAccount** [comment]
[16:03:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'parkour' in plugin ParkourMaker v0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-220]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-220]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-220]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.util.NoSuchElementException
        at com.github.noonmaru.tap.command.ArgumentList.next(ArgumentList.kt:46) ~[?:?]
        at com.github.noonmaru.parkourmaker.command.CommandQuit.onCommand(CommandQuit.kt:29) ~[?:?]
        at com.github.noonmaru.tap.command.CommandSet.onCommand(CommandSet.kt:160) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-220]
        ... 17 more

플러그인 존재하는거 BaeHyeonWooPL (Legacy), ProtocolLib, WorldEdit, Tap, ParkourMaker, Kotlin 일겁니다.

Tap 2.3.1에서 실행했습니다.

**Comment by qogusdn1017-BHW-SecondAccount** [comment]
다른 문제점이 있는지 확인하고 오겠습니다

**Comment by qogusdn1017-BHW-SecondAccount** [comment]
죄송합니다 확인 결과 /parkour quit 만 해서 오류가 뜬거였네요 (지인분이 대신 테스트하셔서)

일단 문제는 해결된거 같으니 이슈 닫도록 하겠습니다.
감사합니다.
