### ISSUE TITLE
Fully Done with issues #8

### ISSUE THREAD

**Issue by ghost** [noonmaru/parkour-maker#8]
- Having issues when the command syntax is not written correctly.

명령 구문을 정확하게 적지 않았을때 그냥 오류가 발생하네요

Error when I run only "/parkour start", "/parkour quit", "/parkour stop" or some kind of it.

```
[02:29:50 INFO]: BaeHyeonWoo issued server command: /parkour start
[02:29:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'parkour' in plugin ParkourMaker v0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-378]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-378]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-378]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-378]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.util.NoSuchElementException
        at com.github.noonmaru.tap.command.ArgumentList.next(ArgumentList.kt:46) ~[?:?]
        at com.github.noonmaru.parkourmaker.command.CommandStart.onCommand(CommandStart.kt:17) ~[?:?]
        at com.github.noonmaru.tap.command.CommandSet.onCommand(CommandSet.kt:160) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-378]
        ... 17 more
```

Think all of them have same problem ; all of them shows same error message.

- About the region pasting(?)

문과 같은 경우 설치는 되는 아이템이 드랍이 되는 경우가 발생됩니다.

게임룰 변경을 하면 드랍이 안되긴 해서 크게 문제될거는 없어보이긴 하네요...

- 아이디어

개인적 생각인데 잘못된 곳에 떨어지거나 플레이어가 죽는 블록에 닿았을때 이전 체크포인트로 돌아가도록 하는건 어떨까요? (이미 있을수도있지만)

또 체크포인트 도착했을때 `채팅에 누군가가 채크포인트를 도착했습니다!` 라는 메시지가 나와도 괜찮을듯 해요.

(맵 공유에 관해 생각해봤는데, schem쓰면 되니 크게 문제될일은 없을듯 하네요.)

**Comment by ghost** [comment]
![오류 발생했을때 플레이어 채팅 화면](https://user-images.githubusercontent.com/36562850/87110635-7a442c00-c2a2-11ea-87f3-6a6bc233d602.png)

![GCP콘솔](https://user-images.githubusercontent.com/36562850/87110689-99db5480-c2a2-11ea-958c-68526facc8a2.png)

게임 작동되는데에는 그렇게 큰 영향은 주지 않지만 그저 궁금해서 물어봅니다. 불쾌하시다면 바로 이슈 닫겠습니다.

**Comment by patrick-choe** [comment]
#9 로 parkour-maker 에 특정 커맨드 사용시 발생하는 NoSuchElementException 오류를 해결해봤습니다, @qogusdn1017

**Comment by ghost** [comment]
확인했습니다! 아이디어 관련해서도 질문을했으니 맨션은 할게요... ㅎㅎ;;

@noonmaru

**Comment by patrick-choe** [comment]
region copy 같은 경우에는 내부 시스템적으로 pasting 과정에서 문 같은 두개 이상의 블록으로 이루어진 블록의 경우 부서지면서 하나의 아이템이 드랍하는것으로 알고 있습니다. (minecraft 내부의 clone 커맨드에서도 확인 가능) 따라서 플러그인에서 이 문제점을 해결하기가 쉽지는 않을 것 같습니다.

**Comment by ghost** [comment]
아 침대랑 비슷하네요... 알겠습니다. 아이디어 관련때문에 이슈는 계속 열것이고, 2~3일 안에 답장 오지않으면 버그는 고쳐진듯하니 그때 이슈 닫을게요

**Comment by noonmaru** [comment]
확인해보겠습니다 이슈는 해결되거나 해결 불가능할경우 닫겠습니다
감사합니다~

**Comment by ghost** [comment]
감사합니다!
